export const ADD_USER = 'ADD_USER';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const IS_EDITING = 'IS_EDITING';
export const RECEIVE_CURRENCIES_SUCCESS = 'RECEIVE_CURRENCIES_SUCCESS';
export const UPDATE_EXPENSES = 'UPDATE_EXPENSES';
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
