export const SAVE_EMAIL = 'SAVE_EMAIL';

export const SAVE_EXPENSE_INFO = 'SAVE_EXPENSE_INFO';

export const ERASE_EXPENSE = 'ERASE_EXPENSE';

export const INCREASE_TOTAL_VALUE = 'INCREASE_TOTAL_VALUE';

export const DECREASE_TOTAL_VALUE = 'DECREASE_TOTAL_VALUE';
